//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <wchar.h>

// ------------------- Function Prototypes --------------------

int32_t __decode_pointer(int32_t result);
void __do_global_ctors(void);
void __main(void);
void _encode_pointer(char * ptr);
int32_t (*mingw_onexit(int32_t (*func)()))();

// --------------------- Global Variables ---------------------

void (**__onexitbegin)() = NULL;
void (**__onexitend)() = NULL;
int32_t g1 = 0; // ebx
int32_t g2 = -1;
int32_t initialized = 0;

// ------------------------ Functions -------------------------

// Address range: 0x401550 - 0x4015ba
int main(int argc, char ** argv) {
    // entry
    __main();
    wprintf(L"%s");
    return 0;
}

// From module:   /build/mingw-w64-crt/src/mingw-w64-v5.0.3/mingw-w64-crt/crt/atonexit.c
// Address range: 0x4015c0 - 0x401672
// Line range:    33 - 53
int32_t (*mingw_onexit(int32_t (*func)()))() {
    int32_t v1 = __decode_pointer(*(int32_t *)&__onexitbegin); // 0x4015cc
    void (**onexitend)() = NULL; // bp-20
    *(int32_t *)&onexitend = v1;
    int32_t v2;
    if (v1 == -1) {
        // 0x4015da
        return _onexit((int32_t (*)())v2);
    }
    // 0x4015f0
    _lock(8);
    *(int32_t *)&onexitend = __decode_pointer(*(int32_t *)&__onexitbegin);
    int32_t v3 = __decode_pointer(*(int32_t *)&__onexitend); // bp-16
    int32_t (*v4)() = __dllonexit((int32_t (*)())v2, &onexitend, (void (***)())&v3); // 0x401635
    _encode_pointer((char *)onexitend);
    int32_t * v5;
    *(int32_t *)&__onexitbegin = (int32_t)&v5;
    _encode_pointer((char *)v3);
    *(int32_t *)&__onexitend = (int32_t)&v5;
    _unlock(8);
    return (int32_t (*)())(int32_t)v4;
}

// From module:   /build/mingw-w64-crt/src/mingw-w64-v5.0.3/mingw-w64-crt/crt/gccmain.c
// Address range: 0x4016e0 - 0x401725
// Line range:    32 - 39
void __do_global_ctors(void) {
    // entry
    g1 = 0;
    int32_t v1; // 0x4016fa
    if (*(int32_t *)((int32_t)&g2 + 4) == 0) {
        // 0x401724
        __pseudo_call(*(int32_t *)(int32_t)&g2);
        v1 = g1 - 1;
        g1 = v1;
        // branch -> 0x4016f3
        while (v1 != 0) {
            // 0x4016f3
            __pseudo_call(*(int32_t *)(4 * v1 + (int32_t)&g2));
            v1 = g1 - 1;
            g1 = v1;
            // continue -> 0x4016f3
        }
        // 0x4016ff
        atexit((void (*)())0x4016a0);
        return;
    }
    int32_t v2 = 1; // 0x401714
    g1 = v2;
    while (*(int32_t *)(4 * (v2 + 1) + (int32_t)&g2) != 0) {
        // 0x401714
        v2++;
        g1 = v2;
        // continue -> 0x401714
    }
    // 0x401724
    __pseudo_call(*(int32_t *)(4 * v2 + (int32_t)&g2));
    v1 = g1 - 1;
    g1 = v1;
    // branch -> 0x4016f3
    while (v1 != 0) {
        // 0x4016f3
        __pseudo_call(*(int32_t *)(4 * v1 + (int32_t)&g2));
        v1 = g1 - 1;
        g1 = v1;
        // continue -> 0x4016f3
    }
    // 0x4016ff
    atexit((void (*)())0x4016a0);
}

// From module:   /build/mingw-w64-crt/src/mingw-w64-v5.0.3/mingw-w64-crt/crt/gccmain.c
// Address range: 0x401730 - 0x40174b
// Line range:    53 - 58
void __main(void) {
    // entry
    if (initialized != 0) {
        // 0x401739
        return;
    }
    // 0x401740
    initialized = 1;
    __do_global_ctors();
}

// Address range: 0x401a70 - 0x401a74
int32_t __decode_pointer(int32_t result) {
    // entry
    return result;
}

// From module:   /build/mingw-w64-crt/src/mingw-w64-v5.0.3/mingw-w64-crt/crt/mingw_helpers.c
// Address range: 0x401a80 - 0x401a84
// Line range:    25 - 28
void _encode_pointer(char * ptr) {
    // entry
    return;
}

// --------------- Statically Linked Functions ----------------

// int32_t atexit(void (*a1)());

// --------------- Dynamically Linked Functions ---------------

// _onexit_t __dllonexit(_onexit_t func, _PVFV ** pbegin, _PVFV ** pend);
// void __cdecl _lock(int locknum);
// _onexit_t _onexit(_onexit_t Function);
// void __cdecl _unlock(int locknum);
// int wprintf(const wchar_t * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.2.0)
// Detected language: C
// Detected functions: 6
// Decompilation date: 2017-12-15 11:35:27
